collab/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('user_module/',include(('user_module.urls','user_module'),namespace='user_module')),

    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name='home'
urlpatterns = [
    path('', views.home, name='homepage'),
    path('login', views.login, name='loginpage'),

    path('password-reset', auth_views.PasswordResetView.as_view(template_name = 'password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'password_reset_confirm.html'), name='password_reset_confirm'),
    
    path('errorlogin', views.errorlogin, name='error_loginpage'),
    path('feedback', views.feedback, name='feedback-page'),
    path('user_module/',include(('user_module.urls','user_module'),namespace='user_module')),
]

user_module/urls.py
from django.urls import path,include

from . import views

app_name='user_module'

urlpatterns = [
    path('skills', views.skills, name='skills-page'),
    path('projects', views.projects, name='projects-page'),
    path('profile', views.profile, name='profile-page'),
    path('logout', views.logout_page, name='logout-page'),
    path('projects/<int:pk>/', views.projects_detailview, name='projects-detail-page'),
    path('skills/<int:pk>/', views.skills_detailview, name='skills-detail-page'),

#project detailview redirection to other pages through nav bar
    path('projects/<int:pk>/projects', views.project_to_project_redirect, name='project-to-project-redirect'),
    path('projects/<int:pk>/skills', views.project_to_skill_redirect, name='project-to-skill-redirect'),
    path('projects/<int:pk>/profile', views.project_to_profile_redirect, name='project-to-profile-redirect'),
    path('projects/<int:pk>/logout', views.project_to_logout_redirect, name='project-to-logout-redirect'),

#skill detailview redirection to other pages through nav bar
    path('skills/<int:pk>/projects', views.skill_to_project_redirect, name='skill-to-project-redirect'),
    path('skills/<int:pk>/skills', views.skill_to_skill_redirect, name='skill-to-skill-redirect'),
    path('skills/<int:pk>/profile', views.skill_to_profile_redirect, name='skill-to-profile-redirect'),
    path('skills/<int:pk>/logout', views.skill_to_logout_redirect, name='skill-to-logout-redirect'),

] 

user_module/models.py
from django.db import models
from django.forms.fields import CharField, ImageField
from django.utils.translation import activate
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from PIL import Image

class project_model(models.Model):
    user = models.CharField(max_length=250)
    project_name        = models.CharField(max_length=250)
    project_description = models.TextField()
    project_git_link    =  models.CharField(max_length=250, blank=True)
    project_date        = models.DateTimeField(default=timezone.localtime)
    def __str__(self):
        return self.project_name

class skill_model(models.Model):
    user = models.CharField(max_length=250)
    skill_name        = models.CharField(max_length=250)
    skill_description = models.TextField()
    skill_link        =  models.CharField(max_length=250, blank=True)
    skill_date        = models.DateTimeField(default=timezone.localtime)
    def __str__(self):
        return self.skill_name

class profile_model(models.Model):
    user     = models.CharField(unique=True, max_length=250)
    email    = models.CharField(unique=True, max_length=250)
    biography       = models.TextField(blank=True)
    phone_number    = PhoneNumberField(blank=True)
    github          = models.CharField(max_length=250, blank=True)
    discord         = models.CharField(max_length=250, blank=True)   

    college_name                = models.CharField(max_length=250, blank=True)
    degree_name                 = models.CharField(max_length=150, blank=True)
    course_name                 = models.CharField(max_length=150, blank=True)
    year_of_joining             = models.CharField(max_length=5, blank=True)
    ongoing_course_semester     = models.CharField(max_length=10, blank=True)
    profile_pic                 = models.ImageField(upload_to='profile_pics', default='default.jpg')
    def __str__(self):
        return self.user
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.profile_pic.path)
        if img.width>300 or img.height>300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

class user_bookmark_model(models.Model):
    user = models.CharField(max_length=200)
    bookmark_id             = models.IntegerField()
    bookmark_name           = models.CharField(max_length=250)
    Bookmark_Type_Choices   = [ ('Skill','Skill'), ('Project','Project')]
    bookmark_type           = models.CharField(max_length=50,choices=Bookmark_Type_Choices)
    bookmark_date           = models.DateTimeField(default=timezone.localtime)
    def __str__(self):
        return self.bookmark_name

user_module/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib.auth import  logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator

from .forms import profile_form, project_form, skill_form , user_bookmark_form
from .models import project_model, profile_model, skill_model, user_bookmark_model

app_name ='user_module'

def projects(request,*args, **kwargs):  
    user_log = request.user
    if user_log.is_authenticated:
        form = project_form()
        public_obj = project_model.objects.all().exclude(user=user_log).order_by('-project_date')
        obj = project_model.objects.all().filter(user = user_log).order_by('-project_date')
        bookmark_obj = user_bookmark_model.objects.all().filter(user = user_log, bookmark_type = 'Project').order_by('-bookmark_date')

        paginator = Paginator(public_obj, 10)
        paginator_1 = Paginator(obj, 10)            
        paginator_2 = Paginator(bookmark_obj, 10)   

        page_number = request.GET.get('page')
        page_number_1 = request.GET.get('page')   #not working as intended  
        page_number_2 = request.GET.get('page')   #not working as intended  

        page_obj = paginator.get_page(page_number)
        page_obj_1 = paginator_1.get_page(page_number_1)
        page_obj_2 = paginator_2.get_page(page_number_2)

        context = {'user':user_log, 'form':form, 'page_obj_1':page_obj_1, 'page_obj_2': page_obj_2 ,'page_obj': page_obj}

        if request.method == 'POST':
            form = project_form(request.POST)

            if form.is_valid():
                form_obj = form.save(commit=False)
                form_obj.user = user_log
                form_obj.save()
                form = project_form()

                context = {'user':user_log, 'form':form, 'message':'success', 'page_obj_1':page_obj_1, 'page_obj_2': page_obj_2, 'page_obj': page_obj}
                return redirect('/user_module/projects')
            else:
                form = project_form()
                context = {'user':user_log, 'form':form, 'message':'Unsuccessfull !!', 'page_obj_1':page_obj_1, 'page_obj_2': page_obj_2, 'page_obj': page_obj}
                return render(request, 'projects.html', context)

        return render(request, 'projects.html', context)
    else:
        return redirect(reverse('home:loginpage'))

def projects_detailview(request,pk):
    user_log = request.user

    if user_log.is_authenticated:
        id = pk

        obj = project_model.objects.all().filter(pk=id)
        obj_user = obj.values('user').first()
        obj_id = obj.values('id').first()
        obj_project_name = obj.values('project_name').first()        
        profile_obj = profile_model.objects.filter(user=str(obj_user['user']))
        bookmark_obj = user_bookmark_model.objects.filter(user=str(user_log)
                                                            ,bookmark_name=str(obj_project_name['project_name'])
                                                            ,bookmark_id=str(obj_id['id'])
                                                            ,bookmark_type='Project')

        delete_bookmark_obj = user_bookmark_model.objects.filter(bookmark_name=str(obj_project_name['project_name'])
                                                                ,bookmark_id=str(obj_id['id'])
                                                                ,bookmark_type='Project')

        form = project_form(request.POST or None, instance = obj.first())
        bookmark_form = user_bookmark_form(request.POST or None)

        if bookmark_obj.count()>0:
            bookmark = True
        else:
            bookmark = False

        context = {'user_log':user_log, 'obj':obj, 'profile_obj':profile_obj, 'form':form,
                     'bookmark_form':bookmark_form, 'bookmark':bookmark}

        if 'submit' in request.POST:

            if 'update' == request.POST.get('submit'):

                if form.is_valid():
                    form_obj = form.save(commit=False)
                    form_obj.user = str(user_log)
                    form_obj.save()
                    return redirect('/user_module/projects/'+str(obj_id['id'])+'/')

            elif 'bookmark' == request.POST.get('submit'):

                if bookmark_form.is_valid():
                    bookmark_form_obj = bookmark_form.save(commit=False)
                    bookmark_form_obj.user = str(user_log)
                    bookmark_form_obj.bookmark_type = 'Project'
                    bookmark_form_obj.bookmark_name = str(obj_project_name['project_name'])
                    bookmark_form_obj.bookmark_id = str(obj_id['id'])
                    bookmark_form_obj.save()
                    return redirect('/user_module/projects/'+str(obj_id['id'])+'/')

            elif 'unbookmark' == request.POST.get('submit'):
                bookmark_obj.delete()
                return redirect('/user_module/projects/'+str(obj_id['id'])+'/')

            elif 'yes' == request.POST.get('submit'):
                obj.delete() 
                return redirect('/user_module/projects')      

        return render(request, 'projects_detailview.html', context)
    else:
        return redirect(reverse('home:loginpage'))


def skills(request, *args, **kwargs): 
    user_log = request.user

    if user_log.is_authenticated:
        form = skill_form()

        public_obj = skill_model.objects.all().exclude(user = user_log).order_by('-skill_date')
        obj = skill_model.objects.all().filter(user = user_log).order_by('-skill_date')
        bookmark_obj = user_bookmark_model.objects.all().filter(user = user_log, bookmark_type = 'Skill').order_by('-bookmark_date')


        paginator = Paginator(public_obj, 10)
        paginator_1 = Paginator(obj, 5)              
        paginator_2 = Paginator(bookmark_obj, 5)    

        page_number = request.GET.get('page')
        page_number_1 = request.GET.get('page') #not working as intended
        page_number_2 = request.GET.get('page') #not working as intended

        page_obj = paginator.get_page(page_number)
        page_obj_1 = paginator_1.get_page(page_number_1)
        page_obj_2 = paginator_2.get_page(page_number_2)

        context = {'user':user_log, 'form':form, 'page_obj_1':page_obj_1, 'page_obj_2': page_obj_2 ,'page_obj': page_obj}

        if request.method == 'POST':
            form = skill_form(request.POST)

            if form.is_valid():
                form_obj = form.save(commit=False)
                form_obj.user = user_log
                form_obj.save()
                form = skill_form()

                context = {'user':user_log, 'form':form, 'page_obj_1':page_obj_1, 'page_obj_2': page_obj_2, 'page_obj': page_obj, 'message':'success'}
                return redirect('/user_module/skills')
            else:
                form = skill_form()
                context = {'user':user_log, 'form':form, 'page_obj_1':page_obj_1, 'page_obj_2': page_obj_2, 'page_obj': page_obj, 'message':'Unsuccessfull !!'}
                return render(request, 'skills.html',context)

        return render(request, 'skills.html',context)
    else:
        return redirect(reverse('home:loginpage')) 

def skills_detailview(request,pk):
    user_log = request.user

    if user_log.is_authenticated:
        id = pk

        obj = skill_model.objects.all().filter(pk=id)
        obj_user = obj.values('user').first()
        obj_id = obj.values('id').first()
        obj_skill_name = obj.values('skill_name').first()
        profile_obj = profile_model.objects.filter(user=str(obj_user['user']))
        bookmark_obj = user_bookmark_model.objects.filter(user=str(user_log)
                                                            ,bookmark_name=str(obj_skill_name['skill_name'])
                                                            ,bookmark_id=str(obj_id['id'])
                                                            ,bookmark_type='Skill')

        delete_bookmark_obj = user_bookmark_model.objects.filter(bookmark_name=str(obj_skill_name['skill_name'])
                                                                ,bookmark_id=str(obj_id['id'])
                                                                ,bookmark_type='Skill')

        form = skill_form(request.POST or None, instance = obj.first())
        bookmark_form = user_bookmark_form(request.POST or None)
        
        if bookmark_obj.count()>0:
            bookmark = True
        else:
            bookmark = False

        context = {'user_log':user_log, 'obj':obj, 'profile_obj':profile_obj, 'form':form,
                     'bookmark_form':bookmark_form, 'bookmark':bookmark}

        if 'submit' in request.POST:

            if 'update' == request.POST.get('submit'):

                if form.is_valid():
                    form_obj = form.save(commit=False)
                    form_obj.user = str(user_log)
                    form_obj.save()
                    return redirect('/user_module/skills/'+str(obj_id['id'])+'/')

            elif 'bookmark' == request.POST.get('submit'):

                if bookmark_form.is_valid():
                    bookmark_form_obj = bookmark_form.save(commit=False)
                    bookmark_form_obj.user = str(user_log)
                    bookmark_form_obj.bookmark_type = 'Skill'
                    bookmark_form_obj.bookmark_name = str(obj_skill_name['skill_name'])
                    bookmark_form_obj.bookmark_id = str(obj_id['id'])
                    bookmark_form_obj.save()
                    return redirect('/user_module/skills/'+str(obj_id['id'])+'/')

            elif 'unbookmark' == request.POST.get('submit'):
                bookmark_obj.delete()
                return redirect('/user_module/skills/'+str(obj_id['id'])+'/')

            elif 'yes' == request.POST.get('submit'):
                obj.delete() 
                delete_bookmark_obj.delete()
                return redirect('/user_module/skills')      

user_module/templates/projects.html
{% extends 'base_user_module.html' %}
{% block title %}Projects | Collabs{% endblock title %}

{% block body %}

<div class="row card-rounded black" style="margin:20px 20px;">
    <div class="col s12">
      
      <h4 class="flow-text center white-text">Projects</h4>
      <ul class="tabs tabs-fixed-width tabs-transparent" style="border-radius: 10px; margin: 20px 0 0 0;">
        <li class="tab col s3"><a href="#test1" class="active flow-text">My Dashboard</a></li>
        <li class="tab col s3"><a href="#test2" class="flow-text">Public Dashboard</a></li>
      </ul>

    </div>

    <div id="test1" class="col s12">
      
      <div class="row">
        <i class="material-icons left white-text" style="padding-left: 20px">view_list</i><h5 class="header white-text lighten-2">My Dashboard</h5>
        
        <div class="col s12 m6">
          
          <div class="card card-rounded blue-grey" style="margin:10px 10px;">
            <div class="card-content card-rounded white-text ">
              
              <span class="card-title flow-text center"><b>Add New Project</b></span>
              <p>Hey ! {{user|capfirst}} you can add your projects by filling the below form</p><br>
              
              <form method='POST' action="projects">
                
                {% csrf_token %}
                <i class=" material-icons right">mode_edit</i>
                <label for="id_project_name" class="white-text"><h6>project :</h6></label>
                {{form.project_name}}
                <i class=" material-icons right">mode_edit</i>
                <label for="id_project_description" class="white-text"><h6>Description :</h6></label>
                {{form.project_description}}
                <i class=" material-icons right">mode_edit</i>
                <label for="id_project_git_link" class="white-text"><h6>Link :<h6></label>
                {{form.project_git_link}}   
                <center><br>
                <button type="submit" name="submit" value="save" class="btn btn-default white hoverable black-text button-rounded"><b>Save</b></button>
                </center>
              
              </form>
            
            </div>
          </div>

        </div>

        <div class="col s12 m6"> 

          <div class="card card-rounded blue-grey" style="margin:10px 10px">
            <div class="card-content white-text">
              
              <span class="card-title flow-text center"><b>Projects you mentioned....</b></span>
              
              <ul class="collection border-none">
                {% for obj in page_obj_1 %}
                  <li class="collection-item hoverable flow-text  blue-grey darken-4" style="margin: 0 20px 5px 20px;">
                    <div>
                      {% if page_obj_1|first|stringformat:'s' == obj.project_name|stringformat:'s' %} 
                        {{obj.project_name|capfirst}}
                        <a href="projects/{{obj.id}}/" class="secondary-content"><i class="material-icons small circle white-text tooltipped"
                        data-position="top" data-tooltip="Open" style="margin:0 0 0 10px;">chevron_right</i></a> <span class="new badge  red darken-4 "></span>                   
                      {% endif %}
                      {% if page_obj_1|first|stringformat:'s' != obj.project_name|stringformat:'s' %} 
                        {{obj.project_name|capfirst}}
                        <a href="projects/{{obj.id}}/" class="secondary-content"><i class="material-icons small circle white-text tooltipped"
                        data-position="top" data-tooltip="Open" style="margin:0 0 0 10px;">chevron_right</i></a>  
                      {% endif %}                       
                    </div>
                  </li>
                {% endfor %}
              </ul>

              <center>
                <ul class="pagination">
                  {% if page_obj_1.has_previous %}
                    <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2" href="?page=1">
                    <i class="material-icons black-text">first_page</i></a></li>
                    <li class="waves-effect"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2" href="?page={{ page_obj_1.previous_page_number }}">
                    <i class="material-icons black-text">chevron_left</i></a></li>
                  {% endif %}

                  {% for num in page_obj_1.paginator.page_range %}
                    {% if page_obj_1.number == num %}
                      <li class="waves-effect hoverable active"><a class="btn btn-info mb-4 purple darken-4 darken-2" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj_1.number|add:'-3' and num < page_obj_1.number|add:'3' %}
                      <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                  {% endfor %}

                  {% if page_obj_1.has_next %}
                    <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ page_obj_1.next_page_number }}">
                    <i class="material-icons">chevron_right</i></a></li>
                    <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ page_obj_1.paginator.num_pages }}">
                    <i class="material-icons">last_page</i></a></li>
                  {% endif %}
                </ul>
              </center><br>

            </div>
          </div>        
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6 l6">
          <div class="card card-rounded blue-grey" style="margin:10px 10px;">
            <div class="card-content white-text">
              <span class="card-title flow-text center"><b>Projects you bookmarked....</b></span>
              <ul class="collection border-none">
                  {% for obj in page_obj_2 %}
                    <li class="collection-item hoverable flow-text  blue-grey darken-4" style="margin: 0 20px 5px 20px;">
                      <div>
                        {% if page_obj_2|first|stringformat:'s' == obj.bookmark_name|stringformat:'s' %}   
                          <a href="projects/{{obj.bookmark_id}}/" class="white-text">{{obj.bookmark_name|capfirst}}
                          <i class="material-icons small circle white-text tooltipped right" data-position="top" data-tooltip="Open">chevron_right</i>
                          <span class="new badge  light-green accent-3 black-text"></span></a>
                        {% endif %}
                        {% if page_obj_2|first|stringformat:'s' != obj.bookmark_name|stringformat:'s' %}   
                          <a href="projects/{{obj.bookmark_id}}/" class="white-text">{{obj.bookmark_name|capfirst}}
                          <i class="material-icons small circle white-text tooltipped right" data-position="top" data-tooltip="Open">chevron_right</i></a>                                        
                        {% endif %}                    
                      </div>
                    </li>
                  {% endfor %}
                </ul>
              <center>
                <ul class="pagination">
                  {% if page_obj_1.has_previous %}
                    <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2" href="?page=1">
                    <i class="material-icons black-text">first_page</i></a></li>
                    <li class="waves-effect"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2" href="?page={{ page_obj_1.previous_page_number }}">
                    <i class="material-icons black-text">chevron_left</i></a></li>
                  {% endif %}
                  {% for num in page_obj_1.paginator.page_range %}
                    {% if page_obj_1.number == num %}
                      <li class="waves-effect hoverable active"><a class="btn btn-info mb-4 purple darken-4 darken-2" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj_1.number|add:'-3' and num < page_obj_1.number|add:'3' %}
                      <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if page_obj_1.has_next %}
                    <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ page_obj_1.next_page_number }}">
                    <i class="material-icons">chevron_right</i></a></li>
                    <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ page_obj_1.paginator.num_pages }}">
                    <i class="material-icons">last_page</i></a></li>
                  {% endif %}
                </ul>
              </center><br>
            </div>
          </div>
        </div>
      </div>    
    </div>

    <div id="test2" class="col s12">
      <div class="row">
      <i class="material-icons left white-text" style="padding-left: 20px">view_list</i><h5 class="header white-text lighten-2">Public Dashboard</h5>
        <div class="col s12">    
          <div class="card card-rounded blue-grey" style="margin:10px 10px;">
            <div class="card-content">
              <span class="card-title black-text flow-text center  white-text"><b>Projects among the Public...</b></span>  
              <div class="row">
              <div class="container">
                {% for project_model in page_obj %}
                 <div class="col s12">        
                  <div class="card card-rounded hoverable black" style="margin:10px 10px;">
                    <div class="card-content white-text">
                      <a href="projects/{{ project_model.id }}/" class="white-text">
                      <span class="card-title center flow-text"><b>{{project_model.project_name|capfirst}}</b></span>
                      <p class="p-justify">{{project_model.project_description|capfirst}}</p><br>
                      <div class="card-action">
                      {{project_model.user|capfirst}}
                      <span class="right">{{project_model.project_date}}</span></a>
                      </div>
                    </div>
                  </div>      
                </div>
                {% endfor %}
                <center>
                  <ul class="pagination">
                    {% if page_obj_1.has_previous %}
                      <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2" href="?page=1">
                      <i class="material-icons black-text">first_page</i></a></li>
                      <li class="waves-effect"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2" href="?page={{ page_obj_1.previous_page_number }}">
                      <i class="material-icons black-text">chevron_left</i></a></li>
                    {% endif %}
                    {% for num in page_obj_1.paginator.page_range %}
                      {% if page_obj_1.number == num %}
                        <li class="waves-effect hoverable active"><a class="btn btn-info mb-4 purple darken-4 darken-2" href="?page={{ num }}">{{ num }}</a></li>
                      {% elif num > page_obj_1.number|add:'-3' and num < page_obj_1.number|add:'3' %}
                        <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ num }}">{{ num }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj_1.has_next %}
                      <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ page_obj_1.next_page_number }}">
                      <i class="material-icons">chevron_right</i></a></li>
                      <li class="waves-effect hoverable"><a class="btn btn-outline-info mb-4 purple darken-4 darken-2 black-text" href="?page={{ page_obj_1.paginator.num_pages }}">
                      <i class="material-icons">last_page</i></a></li>
                    {% endif %}
                  </ul>
                </center>
              </div>
              </div>
            </div>
          </div>
        </div>       
      </div>
    </div>
</div>

{% endblock body %}